---
kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: maven:3.6.1-jdk-11-slim
    commands:
      - mvn package

  - name: bake-stable
    image: plugins/docker
    settings:
      username:
        from_secret: docker_user
      password:
        from_secret: docker_pass
      repo: rubasace/rsocket-chat-server
      tags: stable
    when:
      branch:
        - master

  - name: bake-beta
    image: plugins/docker
    settings:
      username:
        from_secret: docker_user
      password:
        from_secret: docker_pass
      repo: rubasace/rsocket-chat-server
      tags: beta
    when:
      branch:
        - release/*


